# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fac', models.DateField()),
                ('data_scad', models.DateField()),
                ('status', models.CharField(choices=[('achitat', 'Factura achitata'), ('anulat', 'Factura anulata'), ('stornat', 'Factura stornata')], default='', max_length=7)),
                ('emailat', models.CharField(max_length=3)),
                ('id_valuta', models.CharField(max_length=255)),
                ('id_user', models.IntegerField()),
                ('comentarii', models.CharField(max_length=256)),
                ('ctva', models.FloatField()),
                ('externa', models.CharField(max_length=3)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clienti.Client')),
            ],
            options={
                'db_table': 'fac',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FacDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=256)),
                ('um', models.CharField(max_length=256)),
                ('cant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pu_valuta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturi.Fac')),
            ],
            options={
                'db_table': 'fac_det',
                'managed': True,
            },
        ),
    ]
