# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incasari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_incasare', models.DateField()),
                ('suma', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clienti.Client')),
            ],
            options={
                'db_table': 'incasari',
                'managed': True,
            },
        ),
    ]
