# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incasari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.IntegerField()),
                ('data_incasare', models.DateField()),
                ('suma', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'incasari',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('usd', models.DecimalField(db_column='USD', decimal_places=4, max_digits=10)),
                ('eur', models.DecimalField(db_column='EUR', decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'valuta',
                'managed': False,
            },
        ),
    ]
