# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=256)),
                ('j', models.CharField(max_length=256)),
                ('cui', models.CharField(max_length=256)),
                ('adresa', models.CharField(max_length=256)),
                ('cont', models.CharField(max_length=256)),
                ('banca', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=255)),
                ('activ', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'clienti',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('telefon', models.CharField(max_length=256)),
                ('pozitie', models.CharField(max_length=256)),
                ('id_client', models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='clienti.Client')),
            ],
            options={
                'db_table': 'contacte',
                'managed': True,
            },
        ),
    ]
