# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienti', '0002_auto_20171218_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='activ',
            field=models.CharField(choices=[(b'Yes', b'No'), (b'No', b'No')], default=b'Yes', max_length=3),
        ),
    ]
