# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clienti', '0002_auto_20171218_1953'),
        ('clienti', '0003_auto_20171218_1738'),
    ]

    operations = [
    ]
